stages:

  stage_01_data_prepare:
    cmd: python src/stage_01_data_prepare.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_01_data_prepare.py
      - src/utils/common.py 
      - src/utils/preprocess.py
      - config/config.yaml
      - params.yaml
    outs:
      - preprocessed_data/train
      - preprocessed_data/test
      - preprocessed_data/train_file_names.csv
      - preprocessed_data/test_file_names.csv

  stage_02_save_features:
    cmd: python src/stage_02_save_features.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_02_save_features.py
      - src/utils/common.py 
      - src/utils/featurization.py
      - config/config.yaml
      - params.yaml
      - preprocessed_data/train
    outs:
      - encoders/count_encoder.pk 
      - encoders/label_encoder.pk 
      - encoders/tfidf_encoder.pk 