stages:

  stage_00_commit_everything:
    cmd: git commit -m "commiting before dvc run"

  stage_01_data_prepare:
    cmd: python src/stage_01_data_prepare.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_01_data_prepare.py
      - src/utils/common.py 
      - src/utils/preprocess.py
      - config/config.yaml
      - params.yaml
    outs:
      - preprocessed_data/train
      - preprocessed_data/test
      - preprocessed_data/train_file_names.csv
      - preprocessed_data/test_file_names.csv

  stage_02_save_features:
    cmd: python src/stage_02_save_features.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_02_save_features.py
      - src/utils/common.py 
      - src/utils/featurization.py
      - config/config.yaml
      - params.yaml
      - preprocessed_data/train
    outs:
      - encoders/count_encoder.p
      - encoders/label_encoder.p 
      - encoders/tfidf_encoder.p 

  stage_03_train_ML:
    cmd: python src/stage_03_train_ML.py --config=config/config.yaml --params=params.yaml
    deps: 
      - src/stage_03_train_ML.py
      - src/utils/data_loader.py 
      - src/utils/metrics_plots.py 
      - encoders/count_encoder.p 
      - encoders/label_encoder.p 
      - encoders/tfidf_encoder.p 
      - config/config.yaml
      - params.yaml
      - preprocessed_data/train
      - preprocessed_data/test 

  stage_03_train_DL:
    cmd: python src/stage_03_train_DL.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train_DL.py
      - src/utils/data_loader.py
      - src/utils/metrics_plots.py
      - encoders/count_encoder.p
      - encoders/label_encoder.p
      - encoders/tfidf_encoder.p
      - config/config.yaml
      - params.yaml
      - preprocessed_data/train
      - preprocessed_data/test

  stage_03_train_FastText:
    cmd: python src/stage_03_train_FastText.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train_FastText.py
      - src/utils/data_loader.py
      - src/utils/metrics_plots.py
      - encoders/count_encoder.p
      - encoders/label_encoder.p
      - encoders/tfidf_encoder.p
      - config/config.yaml
      - params.yaml
      - preprocessed_data/train
      - preprocessed_data/test
    
  
