preprocess:
  remove_special: True
  remove_stop: True
  stem: True  
  lemm: False
  summy: False
  stem_type: Snow Ball
  lemm_type: Word Net
  test_size: 0.2
  valid_size: 0.15 

feature_extraction: 
  params:
    ngram_range: (1,1)
    max_seq_length: 400 


models: 

  ML:
    multi_ML_models: [naive_bayes, random_forest, svc]
    naive_bayes: 
      params: 
        alpha: [0.1, 0.4, 0.85]
        fit_prior: [True]
    random_forest:  
      params:  
        n_estimators: [100, 300, 1000]
        max_depth: [5, 11, 15]
        min_samples_split: [5, 7, 13]
        random_state: [42]
        max_leaf_nodes: [5, 7, 17]
    svc: 
      params: 
        C: [0.1, 0.5, 0.7]
        degree: [2, 3]
        random_state: [42] 



  DL:
    params:  
      model_name: [LSTM, GRU] 
      bidirectional: [True] 
      take_all_layers_output: [True] 
      #word_embedding: GloVe 
      seq_length: [300]
      batch_size: [64] 
      hidden_dim: [512] 
      lr: [0.001]
      n_layers: [2]
      embedding_dim: [200] 
      drop_proba: [0.7]
      epochs: [18]
      batch_first: [True]


      
  FastText: 
    params: 
      epochs: 20
      dims: 200
      n_grams: 11
      max_ns: 9

  
  DistilBert:
    params:
      epochs: [7]
      lr: [0.00005, 0.0001]
      batch_size: [16]
      model_name: [distilbert-base-uncased]
