preprocess:
  remove_special: True
  remove_stop: True
  stem: False  
  lemm: True
  summy: False
  stem_type: Snow Ball
  lemm_type: Word Net
  test_size: 0.2
  valid_Size: 0.15 

feature_extraction: 
  params:
    ngram_range: (1,1)
    max_seq_length: 400 


models: 
  ML: 
    naive_bayes: 
      params: 
        alpha: 0.5
        fit_prior: True 
    random_forest:  
      params:  
        n_estimators: 1000
        max_depth: 7
        min_samples_split: 7
        random_state: 42
        max_leaf_nodes: 5
    svc: 
      params: 
        C: 0.1
        degree: 3
        random_state: 42 

  DL:
    params:  
      model_name: LSTM 
      bidirectional: True 
      take_all_layers_output: True 
      #word_embedding: GloVe 
      seq_length: 300
      batch_size: 32 
      output_size: 20     # perfect example to explore more about reading one yaml inside another
      hidden_dim: 512 
      lr: 0.001
      n_layers: 2
      embedding_dim: 100 
      drop_proba: 0.7
      epochs: 5 
      batch_first: True 


      
  FastText: 
    params: 
      epochs: 20
      dims: 200
      n_grams: 11
      max_ns: 9
