artifacts:
  ENCODERS:
    encoder_dir_name: encoders
    count_encoder: count_encoder.p
    label_encoder: label_encoder.p
    tfidf_encoder: tfidf_encoder.p
  INPUT_CLASSES:
  - business
  - entertainment
  - politics
  - sport
  - tech
  PREPROCESSED_DATA_DIR: preprocessed_data
  SOURCE_DATA_DIR: source_data
  TEST_FILE_NAMES_CSV: test_file_names.csv
  TRAIN_FILE_NAMES_CSV: train_file_names.csv
  TEMP_MLFLOW_ARTIFACTS_DIR: temp
